### ISSUE TITLE
Add a step for local development

### ISSUE THREAD

**Issue by MarkBennett** [GoogleCloudPlatform/getting-started-ruby#27]
The only thing holding me back from deploying a managed VM is finding a good way to have one set of settings for developing locally (with a local DB, etc.) and another set for when I'm deploying to production.

Sorry if there's an example somewhere and I missed it, but it seems like this tutorial would be a great place to offer some guidance for how to do this. Thanks and keep up the great working. This guide is exactly what I was looking for!

**Comment by remi** [comment]
The configuration files use in this application provide a section for each environment, eg. `development` or `production`.

The [Getting Started documentation](https://cloud.google.com/ruby/getting-started/tutorial-app) demonstrates how to connect to your remote database when developing locally, eg. using [Cloud SQL](https://cloud.google.com/ruby/getting-started/using-cloud-sql) or [Cloud Datastore](https://cloud.google.com/ruby/getting-started/using-cloud-datastore).  You can, however, configure different settings for your development and production environments.

To [configure your database settings](https://cloud.google.com/ruby/getting-started/using-cloud-sql#configure_settings) per environment, edit your [`config/database.yml`](https://github.com/GoogleCloudPlatform/getting-started-ruby/blob/7123444270725b9ff2ad4b59ddd075e2e120017f/2-cloud-sql/config/database.example.yml) file:

```yaml
mysql_settings: &mysql_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: your-mysql-user-here
  # ...

development:
  <<: *mysql_settings

production:
  <<: *mysql_settings
```

For this tutorial, the development and production settings are shared.  To use different settings, update this file like so:

```yaml
development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: your-DEVELOPMENT-mysql-user-here
  # ...

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: your-PRODUCTION-mysql-user-here
  # ...
```

You can do the same for your [`config/settings.yml`](https://github.com/GoogleCloudPlatform/getting-started-ruby/blob/7123444270725b9ff2ad4b59ddd075e2e120017f/4-auth/config/settings.example.yml) file, eg. as is used to configure [Cloud Storage uploads](https://cloud.google.com/ruby/getting-started/using-cloud-storage) or [Google Authentication](https://cloud.google.com/ruby/getting-started/authenticate-users):

```yaml
default: &default
  oauth2:
    client_id: your-client-id
    # ......

development:
  <<: *default

production:
  <<: *default
```

Can be changed to:

```yaml
development:
  oauth2:
    client_id: your-client-id
    # ......

production:
  oauth2:
    client_id: your-client-id
    # ......
```
